UpDotNetWeb/Controllers/PageController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Web;
using UpDotNetLib;
using UpDotNetLib.Models.Response;
using UpDotNetWeb.Contexts;
using UpDotNetWeb.Models.DbModel;
using UpDotNetWeb.Models.ViewModel;

namespace UpDotNetWeb.Controllers
{
    public class PageController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public PageController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var guid = User.GetObjectId();

            var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Guid == guid);
            if (user == null)
            {
                user = (await _dbContext.Users.AddAsync(new UserDbModel
                {
                    Guid = guid
                })).Entity;
            }
            await _dbContext.SaveChangesAsync();
            
            return View(new IndexViewModel {User = user});
        }

        [Authorize]
        public async Task<IActionResult> UserSettings()
        {
            var guid = User.GetObjectId();
            var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Guid == guid);

            return View(new UserSettingsViewModel {User = user, TokenChecked = false});
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UserSettings(string upApiKey)
        {
            var api = new Api(upApiKey);
            var guid = User.GetObjectId();
            var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Guid == guid);
            PingResponseModel response;
            try
            {
                response = await api.PingApi();
            }
            catch (Http.HttpException e)
            {
                return View(new UserSettingsViewModel
                {
                    User = user,
                    CheckResult = false,
                    TokenChecked = true,
                    Message = e.Message
                });
            }
            user.UpApiKey = upApiKey;
            await _dbContext.SaveChangesAsync();
            return View(new UserSettingsViewModel
                {User = user, TokenChecked = true, CheckResult = true, Message = response.Meta.StatusEmoji});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UpDotNetWeb/Controllers/TransactionController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Web;
using UpDotNetLib;
using UpDotNetWeb.Contexts;
using UpDotNetWeb.Models.ViewModel;

namespace UpDotNetWeb.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public TransactionController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index(string accountId = null)
        {
            var guid = User.GetObjectId();
            var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Guid == guid);
            var transactions = await new Api(user.UpApiKey).GetTransactionList(accountId);
            return View(new TransactionListViewModel {User = user, Transactions = transactions});
        }
        
        public async Task<IActionResult> Page(string pageUrl)
        {
            var guid = User.GetObjectId();
            var user = await _dbContext.Users.FirstOrDefaultAsync(u => u.Guid == guid);
            var pageUri = new Uri(pageUrl);
            // Theoretically it'd be possible to craft a request and reveal the API token to a third party
            // Though API keys aren't really secure but maybe this'll change in the future
            if (pageUri.Host != "api.up.com.au")
            {
                return BadRequest("pageUrl doesn't appear to be an Up API URL");
            }
            var transactions = await new Api(user.UpApiKey).GetTransactionListPage(pageUri);
            return View("Index", new TransactionListViewModel {User = user, Transactions = transactions});
        }
    }
}

UpDotNetWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UpDotNetWeb</title>
    <link rel="stylesheet" href="~/lib/bulma/dist/css/bulma.min.css"/>
    <link rel="stylesheet" href="~/lib/forkawesome/dist/css/fork-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="container">
            <div id="navbar" class="navbar-menu is-active">
                <div class="navbar-start">
                    <a class="navbar-item" asp-controller="Account" asp-action="Index">Accounts</a>
                    <a class="navbar-item" asp-controller="Transaction" asp-action="Index">Transactions</a>
                    <a class="navbar-item" href="#">Notifications</a>
                    <a class="navbar-item" href="#">Settings</a>
                </div>
                
                <div class="navbar-end">
                    <div class="navbar-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="Page" asp-action="UserSettings" class="navbar-item">@User.Identity.Name</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    @RenderBody()
</div>
</body>
</html>